from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    # DeepSeek
    deepseek_api_key: str = ""
    deepseek_base_url: str = "https://api.deepseek.com"
    deepseek_model: str = "deepseek-chat"
    deepseek_request_timeout: int = 60

    # End-to-end request and stage budgets. Each retry gets a fresh attempt cap,
    # but all attempts still share the task and request deadlines.
    agent_request_timeout_seconds: float = 60.0
    safety_llm_timeout_seconds: float = 3.0
    classification_timeout_seconds: float = 5.0
    context_timeout_seconds: float = 8.0
    routing_timeout_seconds: float = 1.0
    memory_timeout_seconds: float = 8.0
    rag_timeout_seconds: float = 8.0
    tool_timeout_seconds: float = 5.0
    nutrition_agent_timeout_seconds: float = 25.0
    environment_agent_timeout_seconds: float = 15.0
    exercise_agent_timeout_seconds: float = 25.0
    llm_attempt_timeout_seconds: float = 12.0
    specialist_llm_timeout_seconds: float = 8.0
    final_generation_timeout_seconds: float = 20.0
    post_process_timeout_seconds: float = 3.0
    chat_persistence_timeout_seconds: float = 3.0

    # Evaluation is intentionally outside the product response deadline.
    judge_timeout_seconds: float = 30.0

    # Optional LLM enhancement for specialist agents.
    # Baseline plans/advice are still generated by tools and rules.
    exercise_llm_refine_enabled: bool = False
    environment_llm_advice_enabled: bool = False

    # JWT
    jwt_secret_key: str = "dev-secret-key-change-in-production"
    jwt_algorithm: str = "HS256"
    jwt_expire_hours: int = 24

    # Database
    database_url: str = "sqlite+aiosqlite:///./data/health.db"

    # Production RAG: Elasticsearch BM25 + DashScope dense vector search.
    rag_index_name: str = "ai_health_knowledge"
    rag_top_k: int = 5
    rag_candidate_k: int = 20
    rag_seed_on_empty: bool = True
    rag_embedding_model: str = "dashscope-text-embedding-v4"
    rag_embedding_batch_size: int = 10
    dashscope_api_key: str = ""
    dashscope_base_url: str = "https://dashscope.aliyuncs.com/compatible-mode/v1"
    dashscope_embedding_model: str = "text-embedding-v4"
    dashscope_embedding_dimension: int = 1024
    dashscope_request_timeout: int = 60
    rag_vector_weight: float = 0.65
    rag_bm25_weight: float = 0.35
    rag_use_reranker: bool = False
    rag_reranker_model: str = "bge-reranker-base"
    rag_warmup_on_startup: bool = False
    memory_index_name: str = "ai_health_long_term_memory"
    memory_top_k: int = 6
    memory_candidate_k: int = 16
    memory_vector_weight: float = 0.7
    memory_bm25_weight: float = 0.3
    memory_max_days: int = 365
    memory_write_enabled: bool = True
    memory_use_llm_supplement: bool = True
    profile_use_llm_supplement: bool = True
    profile_llm_min_confidence: float = 0.75
    profile_high_risk_confirmation: bool = True
    elasticsearch_url: str | None = None
    elasticsearch_username: str | None = None
    elasticsearch_password: str | None = None
    elasticsearch_api_key: str | None = None

    # Redis
    redis_host: str = "127.0.0.1"
    redis_port: int = 6379
    redis_db: int = 0
    redis_password: str | None = None

    # Rate limiting
    rate_limit_enabled: bool = True
    rate_limit_general: int = 100
    rate_limit_window_minutes: int = 15
    rate_limit_llm: int = 20
    rate_limit_llm_window_minutes: int = 60
    max_request_body_bytes: int = 5 * 1024 * 1024
    max_upload_body_bytes: int = 50 * 1024 * 1024
    max_knowledge_pdf_bytes: int = 30 * 1024 * 1024

    model_config = {"env_file": ".env", "env_file_encoding": "utf-8"}


settings = Settings()
